### ISSUE TITLE
Cmake error on plugin creation --Configuration error

### ISSUE THREAD

**Issue by jobish** [zeek/zeek-aux#12]
Hi ,
I was created a test plugin using init-plugin script ( based on the following documentation https://docs.zeek.org/en/stable/devel/plugins.html)   , but   following error's occurred on compilation time , any help would be really appreciated.
Platform: 
**I was cloned latest ZEEK , ZEEK-bifcl, zeek-aux script ( all repository cloned Recursively )
Os :Centos 7 / Repositories/SCL enabled for GCC version 7 .........**

Commands :
 ./configure --enable-debug --with-bifcl=/opt/dev/zeek_plugins/bifcl/ --zeek-dist=/opt/dev/zeek1

Build Directory        : build
Zeek Source Directory   : /opt/dev/zeek1
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success
-- Zeek executable      :
-- Zeek source          : /opt/dev/zeek1
-- Zeek build           : /opt/dev/zeek1/build
-- Zeek install prefix  : /usr/local/zeek
-- Zeek plugin directory: /usr/local/zeek/lib/zeek/plugins
-- Zeek debug mode      : true
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    ZEEK_DIST

---------------------------
 **after the make command** 

 [Makefile:12: build-it] Error 1 (ignored)
( cd build && make )
make[1]: Entering directory '/opt/test/rot13-plugin/build'
make[2]: Entering directory '/opt/test/rot13-plugin/build'
make[3]: Entering directory '/opt/test/rot13-plugin/build'
Scanning dependencies of target bif-plugin-Demo_Rot13-rot13.bif
make[3]: Leaving directory '/opt/test/rot13-plugin/build'
make[3]: Entering directory '/opt/test/rot13-plugin/build'
[ 11%] [BIFCL] Processing src/rot13.bif
/bin/sh: /opt/dev/zeek_plugins/bifcl: Is a directory
make[3]: *** [CMakeFiles/bif-plugin-Demo_Rot13-rot13.bif.dir/build.make:65: rot13.bif.h] Error 1
make[3]: Leaving directory '/opt/test/rot13-plugin/build'
make[2]: *** [CMakeFiles/Makefile2:146: CMakeFiles/bif-plugin-Demo_Rot13-rot13.bif.dir/all] Error 2
make[2]: Leaving directory '/opt/test/rot13-plugin/build'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/opt/test/rot13-plugin/build'
make: *** [Makefile:13: build-it] Error 2

**Comment by jsiwek** [comment]
> ./configure --enable-debug --with-bifcl=/opt/dev/zeek_plugins/bifcl/ --zeek-dist=/opt/dev/zeek1

> [ 11%] [BIFCL] Processing src/rot13.bif
> /bin/sh: /opt/dev/zeek_plugins/bifcl: Is a directory

That's showing a problem in how you used `-with-bifcl=`, try changing that to point directly at the `bifcl` executable, not the directory.

**Comment by jobish** [comment]
@jsiwek  thanks ,its worked ..
