### ISSUE TITLE
Migrate the CT log list dependency from v1 to v3

### ISSUE THREAD

**Issue by roger2hk** [zeek/zeek-aux#30]
The latest CT log list URL is https://www.gstatic.com/ct/log_list/v3/log_list.json.

https://github.com/zeek/zeek-aux/blob/ce360d19cd2298146de8d59ce5f7ae85c7f83056/devel-tools/gen-ct-list.pl#L14

Reference: https://github.com/google/certificate-transparency-community-site/blob/master/docs/google/known-logs.md

**Comment by roger2hk** [comment]
Both the v1 and v2 CT log lists will be turned down on 17 October 2022.
https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/fX_AG-HUAQAJ

**Comment by timwoj** [comment]
Is this just a matter of switching the URL used?

**Comment by roger2hk** [comment]
The CT log list migration from v2 to v3 is a matter of switching the URL. However, zeek-aux depends on log list v1. The data schema is not fully backward compatible.

https://github.com/zeek/zeek-aux/blob/ce360d19cd2298146de8d59ce5f7ae85c7f83056/devel-tools/gen-ct-list.pl#L45-L53

Here are the log list schemas of v1 and v3.
https://www.gstatic.com/ct/log_list/log_list_schema.json
https://www.gstatic.com/ct/log_list/v3/log_list_schema.json

**Comment by 0xxon** [comment]
Thank you - I  will take a look at it.

I am sorry that this flew under the radar for a while - I just did not notice the issue.

**Comment by roger2hk** [comment]
Thanks for working on that. Let me know if you need any help.

**Comment by roger2hk** [comment]
@0xxon Is this issue going to be addressed before the turndown deadline?

**Comment by timwoj** [comment]
I just talked to @0xxon and she said yes, she'll take care of it.
