### ISSUE TITLE
zeek-aux man page does not include -m, -M options

### ISSUE THREAD

**Issue by william-stearns** [zeek/zeek-aux#39]
zeek-cut.1 does not include the -m and -M options in zeek-cut.  The top of the file notes that it's generated by help2man , but it appears this may not have been run after the the addition of -m and -M to zeek-cut.c (in PR15 in August of 2020).
    Here are the needed lines:

.TP
\fB\-m\fR
Include the first format header block in the output in minimal view.
.TP
\fB\-M\fR
Include all format header blocks in the output in minimal view.

**Comment by ckreibich** [comment]
Oh wow — Bill, hi!!! Thank you very much. :-)
